name: Weekly AQI File

on:
  schedule:
    - cron: '0 6 * * 1'  # At 00:05 on the 1st of every month (UTC)
  workflow_dispatch:     # Optional: lets you run it manually from GitHub UI

jobs:
  merge_weekly_aqi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run AQI monthly merge script
        run: |
          python weekly_data_file.py

      - name: Upload monthly AQI Excel file as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-aqi-report
          path: weekly_charts/*.xlsx
