name: Weekly AQI File

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 06:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  merge_weekly_aqi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run AQI weekly merge script
        run: python weekly_data_file.py

      - name: Commit and push weekly AQI Excel file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git pull origin ${{ github.ref_name }}

          if [ -n "$(git status --porcelain weekly_charts/)" ]; then
            git add weekly_charts/*.xlsx
            git commit -m "📊 Weekly AQI Report: committed by GitHub Actions on $(date +'%Y-%m-%d')"
            git push
          else
            echo "⚠️ No new or modified files to commit."
          fi
